POST http://localhost:5000/api/employees/create
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@examp2le.com",
    "mobile": "1234567890",
    "designation": "Software Engineer",
    "companyName": "Tech Corp"
}

###
GET http://localhost:5000/api/employees
###
PUT http://localhost:5000/api/employees/update/69ca2a693e7f1eaa0b9b4d2b
Content-Type: application/json

{
  "designation": "Senior Developer"
}
###
DELETE http://localhost:5000/api/employees/delete/69ca2a167771bb1be84212cd